### ISSUE TITLE
Feature: Support custom options for fields

### ISSUE THREAD

**Issue by mcdoker18** [mitallast/openapi2proto#1]
We need to mark a field of golang structure with a custom tag.
Gogo supports it using the [moretags custom option](https://github.com/gogo/protobuf/blob/master/extensions.md#more-serialization-formats).
I propose to support [custom options](https://developers.google.com/protocol-buffers/docs/overview#options) for fields using the following design:
```yaml
openapi: 3.0.1
x-proto-package: mypackage
x-proto-import:
  - "github.com/gogo/protobuf/gogoproto/gogo.proto"
info:
  title: User
  version: 1.0.0
paths: {}
components:
  schemas:
    User:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          x-proto-option:
            "gogoproto.moretags": 'sensitive:"true"'
          type: string
```

Openapi2proto must generate the following proto file:

```protobuf
syntax = "proto3";

package mypackage;

import "google/api/annotations.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message User {
   string name = 1;
   string password = 2 [(gogoproto.moretags) = 'sensitive:"true"'];
}
```

Custom options may be attached to a field of any type. The number of options is more or equal to zero.

**Comment by mitallast** [comment]
fixed in b6945c5a295fa8b43ce1f60a1ce33acedf04d3ea
